---

- name: removes subscription nag box
  include: remove-nag.yml
  when: remove_nag

- name: remove enterprise repos
  include: remove-enterprise-repo.yml
  when: remove_enterprise_repo

- name: setup community repo
  include_tasks: add-community-repo.yml
  when: enable_community_repo