---
  # Adapted from https://gist.github.com/whiskerz007/53c6aa5d624154bacbbc54880e1e3b2a
  - name: Copy DPkg override
    copy:
      src: no-nag-script
      dest: /etc/apt/apt.conf.d/no-nag-script
      mode: 0644
      owner: root
    register: copy

  - name: Re-install package to apply changes
    shell: apt-get --reinstall install proxmox-widget-toolkit
    when: copy.changed